name: Push docker image to registry

on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag rafsaf/gatsby-backroad:latest

      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login https://registry.rafsaf.pl \
           -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          docker image tag rafsaf/gatsby-backroad:latest registry.rafsaf.pl/rafsaf/gatsby-backroad:latest
          docker image push registry.rafsaf.pl/rafsaf/gatsby-backroad:latest
